from dataclasses import field
from marshmallow import Schema, fields

class Paciente_Schema(Schema):
    pacCodigoPaciente = fields.Str()
    pacTipoDocumento = fields.Str()
    pacNombres = fields.Str()
    pacApellidos = fields.Str()
    pacSexo = fields.Str()
    pacFechaNac = fields.Str()
    pacLugarNacimiento = fields.Str()
    ciuId = fields.Int()
    pacCorreoElectronico = fields.Str()
    nacId = fields.Int()
    pacTelefono = fields.Str()
    pacDireccion = fields.Str()
    segId = fields.Int()
    pacHijos = fields.Int()
    pacEstadoCivil = fields.Str()
    eduId = fields.Int()
    sitlabId = fields.Int()
    pacLatitud = fields.Float()
    pacLongitud = fields.Float()
    pacCreacionUsuario = fields.Str()
    pacCreacionFecha = fields.Str()
    pacCreacionHora = fields.Str()
    pacModificacionUsuario = fields.Str()
    pacModificacionFecha = fields.Str()
    pacModificacionHora = fields.Str()
    operacion = fields.Str()